{% set name = "bbf" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bbf-{{ version }}.tar.gz
  sha256: b48dcbebdc77262136f27cddfa5e187f0fbef167f32bd71c1e10a0759b2a2587

build:
  skip: true  # [py<39 or win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake >=3.18
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - make
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - nanobind >=1.3.2  # [build_platform != target_platform]
  host:
    - python
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - scikit-build-core >=0.4.3
    - nanobind >=1.3.2
    - pip
  run:
    - python
    - astropy
    - fastparquet
    - getcalspec
    - healpy
    - matplotlib-base
    - numpy
    - pandas
    - platformdirs
    - scikit-sparse
    - scipy >=1.10
    - sncosmo
    - sparse_dot_mkl  # [not arm64]

test:
  imports:
    - bbf
  commands:
    - pip check
    - pip install gaiaxpy lemaitre-bandpasses git+https://github.com/nregnault/sncosmo.git
    - pytest -v tests
  source_files:
    - tests
  requires:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - git
    - pip
    - pytest
    - pytest-cov

about:
  home: https://gitlab.in2p3.fr/lemaitre/bbf
  summary: Fast computation of broadband fluxes and magnitudes
  description: A module to evaluate the broadband fluxes and magnitudes of spectrophotometric standards.

  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mmmaat
